### PR TITLE
Reveal improvements + Frontend fixes

### PR DESCRIPTION
**Pull request by jameshi16**
# Changes

- A better reveal page!
    image
- Chinese / Japanese characters are now scaled properly on the podium
- Make search respond slightly slower (performance requirement for a future change)
- Move down `container` to `page.svelte` so that the burger menu remains on the left
- Remove yippie :^)
- Public Alpha disclaimer moved to menu

## Related Cards

Fixes https://github.com/orgs/vanorsigma/projects/1?pane=issue&itemId=75303750 apart from being a unique spontaneous PR

### CODE REVIEW

**Comment by jameshi16** [comment]
These changes are deployed to https://vanorsigma.github.io/neuro-chat-elo

**Comment by jameshi16** [comment]
> works for me (after fighting to get protobuf working, it didn't let me run `npm run compileProtos` because I was missing the `src/gen/` folder).

Should have been fixed in #22, but I think this branch isn't up-to-date.

> Not sure how I feel about the Skip button staying as skip once the animation finishes - imo it sorta implies its going to end on its own or something?

You're right, I'll update it

**Comment by Gaijutsu** [comment]
I like the look of the new reveal. Have you tried keeping the Overall card on top during the reveal animation? That way the others cards will slide out from underneath instead of appearing in front.

**Comment by jameshi16** [comment]
- Updated to turn "Skip" into "Continue"
- Overall now stands above all

**Review by Gaijutsu — APPROVED** [review]

**Pull request merged**
